version: '3'
services:

  #PHP Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: cloudsigma.com/php
    container_name: backend
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: backend
      SERVICE_TAGS: dev
      working_dir: /var/www/html/

    volumes:
      - ./backend:/var/www/html/
      - ./backend/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9000:9000"
    networks:
      - app-network

  #Node/VueJs Serivce    
  frontend:
    stdin_open: true
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    expose:
      - "80"
    ports:
      - "8080:8080"
      - "8082:8082"
    networks:
      - app-network

  #Nginx Service
  webserver:
    build:
      context: ./backend/nginx
      dockerfile: Dockerfile
    container_name: webserver
    restart: unless-stopped
    tty: true
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    networks:
      - app-network

  # #MySQL Service
  # db:
  #   image: mysql:5.7.22
  #   container_name: db
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_DATABASE: app_user_db
  #     MYSQL_ROOT_PASSWORD: root
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql
  #   volumes:
  #     - dbdata:/var/lib/mysql/
  #     - ./backend/mysql/my.cnf:/etc/mysql/my.cnf
  #   networks:
  #     - app-network

  # #PHPMyadmin Service
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   links:
  #     - db
  #   environment:
  #     PMA_HOST: db
  #     PMA_PORT: 3306
  #     PMA_ARBITRARY: 1
  #   restart: always
  #   ports:
  #     - 8085:80
  #   networks:
  #     - app-network

  #Mongodb service
  mongo:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./backend/database/mongodb/db:/data/db
    command: [ --auth ]
    networks:
      - app-network

  #Mongo-esrpress service
  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_URL=mongodb://root:root@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
